# -*- coding: utf-8 -*-
"""DataScienceEcosystem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10jRJmppl2u6UD9hEaHCRxIQAlqatET8k

#Data Science Tools and Ecosystem

#In this notebook, Data Science Tools and Ecosystem are summarized.

#Some of the popular languages that Data Scientists use are:
1. Python
2. R
3. SQL

#Some of the commonly used libraries used by Data Scientists include:
1. Numpy
2. Scikitlearn
3. Matplotlib

#Data Science Tools
-------------------
|Jupyter Notebook| 
-------------------
| RStudio|
-------------------
| Google Colab |
-------------------
| GitLab|

###Below are a few examples of evaluating arithmetic expressions in Python
"""

(3*4)+5

200/60

"""**Objectives:**


*   Python
*   R
*   GitLab
*   RStudio

##Author
Saurav Deb
"""

